### ISSUE TITLE
"out the sum of the numebigrators divided by the sum of the denominators"

### ISSUE THREAD

**Issue by ToonTalk** [acerix/rational.js#2]
From http://acerix.github.io/rational.js/bigrat.html

Is "numebigrators" an editing mistake?

Very nice package by the way.

**Comment by acerix** [comment]
Thanks for the comment, I have fixed the documentation.

bigrat.js is based on rat.js, and I had done a quick search/replace to rename the class which also matched the "rat" in nume**rat**ors
