### ISSUE TITLE
Error from: bigrat.fromDecimal(511.99999999999994)

### ISSUE THREAD

**Issue by ToonTalk** [acerix/rational.js#3]
bigrat.fromDecimal(511.99999999999994)
VM52 rationaljs.js:143 Uncaught Error: Bad digit for radix 10(…)b.parse @ VM52 rationaljs.js:143b @ VM52 rationaljs.js:68bigrat.fromDecimal_copy @ VM52 rationaljs.js:1161bigrat.fromDecimal @ VM52 rationaljs.js:1142(anonymous function) 

Using today's http://acerix.github.com/rational.js/releases/rationaljs.alpha.js

**Comment by acerix** [comment]
Thanks for the report, now fixed

http://jsfiddle.net/2cp7rjwq/

**Comment by ToonTalk** [comment]
Great, thanks for responding so quickly.
